### PR TITLE
sundry words

### PR DESCRIPTION
**Pull request by GordonCharlton**
Mostly stuff that was considered for The Book of Quackery but omitted for the sake of brevity. Also a brainfuck interpreter.

### CODE REVIEW

**Comment by olus2000** [comment]
Oh gosh, I didn't expect anyone to actually notice the existence of ALEx 😮
No time now, will look into it in a few weeks. Thanks for sharing your work!

**Review by olus2000 — APPROVED** [review]
Loving the new vocabulary. Here are some of my notes:

1. I wonder if `brainfuck` wouldn't be better with its parameters swapped. It's the natural order in the stack languages that parameters go before the function, so the order `<input> <program> brainfuck` seems more intuitive. It would also allow for (a bit) simpler brainfuck-based functions with structure `[ <program> brainfuck ]` loosing an additional swap, or actually probably moving it into the implementation of `brainfuck`.

2. `higher-order.qky` has a header stating that `[ this ] is sundry.qky`

3. There's a typo in line 16 of `sundry.qky`, a misplaced dot.

I also need to find a better way of licensing/crediting to allow other contributors to change files that they are not the authors of. That's just a loose remark.

Other than that it's a wide variety of well implemented words, I'll be glad to include them into ALEx. If you don't respond or change anything in about a week or so I'll fix 2. and 3. and merge this into my main branch.

**Comment by GordonCharlton** [comment]
1. Agreed. `brainfuck` amended accordingly.
2. and 3. Oops. Fixed.

I'm happy for my code to be public domain. The Book of Quackery is copyright, but not Quackery itself.

Sending a push request. Will send a second push request for one more thing; a binary search.

**Review by olus2000 — APPROVED** [review]
There is a loose binary file called ".DS_Store" in your branch, I'll go ahead and add it to ".gitignore". I also presume that line 20 of "binary-search.qky" should say:

> The **next** item on the stack is the nest of ordered items

instead of:

> The **nest** item on the stack is the nest of ordered items

I'll just go ahead with the merge and fix these afterwards. Thanks for sharing your work!

**Comment by GordonCharlton** [comment]
That ".DS_Store" is something MacOS puts in all of its directories. Perfectly safe to .gitignore.

Yes, "next".

My pleasure.

**Pull request merged**
